scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'postgres_local'
    static_configs:
      - targets: ['127.0.0.1:9187']

  - job_name: "kafka-exporter"
    static_configs:
      - targets: ["kafka-exporter:9308"]
    scrape_interval: 30s
    scrape_timeout: 10s
