global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: "kafka-dev"

rule_files:
  # - "kafka_rules.yml"

scrape_configs:
  - job_name: "kafka-exporter"
    static_configs:
      - targets: ["kafka-exporter:9308"]
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: /metrics

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    scrape_interval: 60s
